from dataclasses import field
from pydantic.dataclasses import dataclass
from .utils import null_if_empty

@dataclass
class MiRRecord:
    """
    Dataclass representing patient microRNA float measurements.
    """
    id: str = field(metadata={'mapped_to': 'ID'})
    hsa_miR_1539: float = field(metadata={'mapped_to': 'hsa-miR-1539', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6840_3p: float = field(metadata={'mapped_to': 'hsa-miR-6840-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6836_3p: float = field(metadata={'mapped_to': 'hsa-miR-6836-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4667_5p: float = field(metadata={'mapped_to': 'hsa-miR-4667-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_208a_5p: float = field(metadata={'mapped_to': 'hsa-miR-208a-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6885_5p: float = field(metadata={'mapped_to': 'hsa-miR-6885-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_1306_5p: float = field(metadata={'mapped_to': 'hsa-miR-1306-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_3184_5p: float = field(metadata={'mapped_to': 'hsa-miR-3184-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4649_5p: float = field(metadata={'mapped_to': 'hsa-miR-4649-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6859_3p: float = field(metadata={'mapped_to': 'hsa-miR-6859-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6829_3p: float = field(metadata={'mapped_to': 'hsa-miR-6829-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_3622a_3p: float = field(metadata={'mapped_to': 'hsa-miR-3622a-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4664_3p: float = field(metadata={'mapped_to': 'hsa-miR-4664-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6776_3p: float = field(metadata={'mapped_to': 'hsa-miR-6776-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_135a_3p: float = field(metadata={'mapped_to': 'hsa-miR-135a-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6875_5p: float = field(metadata={'mapped_to': 'hsa-miR-6875-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_3646: float = field(metadata={'mapped_to': 'hsa-miR-3646', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_3614_5p: float = field(metadata={'mapped_to': 'hsa-miR-3614-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_128_1_5p: float = field(metadata={'mapped_to': 'hsa-miR-128-1-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6813_3p: float = field(metadata={'mapped_to': 'hsa-miR-6813-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6752_5p: float = field(metadata={'mapped_to': 'hsa-miR-6752-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_204_3p: float = field(metadata={'mapped_to': 'hsa-miR-204-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6806_5p: float = field(metadata={'mapped_to': 'hsa-miR-6806-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_1538: float = field(metadata={'mapped_to': 'hsa-miR-1538', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6887_3p: float = field(metadata={'mapped_to': 'hsa-miR-6887-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_5088_3p: float = field(metadata={'mapped_to': 'hsa-miR-5088-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6743_5p: float = field(metadata={'mapped_to': 'hsa-miR-6743-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4274: float = field(metadata={'mapped_to': 'hsa-miR-4274', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_5585_3p: float = field(metadata={'mapped_to': 'hsa-miR-5585-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4787_5p: float = field(metadata={'mapped_to': 'hsa-miR-4787-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_320b: float = field(metadata={'mapped_to': 'hsa-miR-320b', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6870_3p: float = field(metadata={'mapped_to': 'hsa-miR-6870-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_199a_5p: float = field(metadata={'mapped_to': 'hsa-miR-199a-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4290: float = field(metadata={'mapped_to': 'hsa-miR-4290', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_6721_5p: float = field(metadata={'mapped_to': 'hsa-miR-6721-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4728_3p: float = field(metadata={'mapped_to': 'hsa-miR-4728-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_3691_5p: float = field(metadata={'mapped_to': 'hsa-miR-3691-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4440: float = field(metadata={'mapped_to': 'hsa-miR-4440', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_874_3p: float = field(metadata={'mapped_to': 'hsa-miR-874-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_27a_3p: float = field(metadata={'mapped_to': 'hsa-miR-27a-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_2278: float = field(metadata={'mapped_to': 'hsa-miR-2278', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_150_3p: float = field(metadata={'mapped_to': 'hsa-miR-150-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4716_3p: float = field(metadata={'mapped_to': 'hsa-miR-4716-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_211_5p: float = field(metadata={'mapped_to': 'hsa-miR-211-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_125a_5p: float = field(metadata={'mapped_to': 'hsa-miR-125a-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_4741: float = field(metadata={'mapped_to': 'hsa-miR-4741', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_3122: float = field(metadata={'mapped_to': 'hsa-miR-3122', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_3180_5p: float = field(metadata={'mapped_to': 'hsa-miR-3180-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_574_3p: float = field(metadata={'mapped_to': 'hsa-miR-574-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_150_5p: float = field(metadata={'mapped_to': 'hsa-miR-150-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_133b: float = field(metadata={'mapped_to': 'hsa-miR-133b', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_30c_5p: float = field(metadata={'mapped_to': 'hsa-miR-30c-5p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_212_3p: float = field(metadata={'mapped_to': 'hsa-miR-212-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_92b_3p: float = field(metadata={'mapped_to': 'hsa-miR-92b-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    hsa_miR_504_3p: float = field(metadata={'mapped_to': 'hsa-miR-504-3p', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    ath_miR_159a: float = field(metadata={'mapped_to': 'ath-miR-159a', 'transform': lambda x: null_if_empty(x, lambda v: float(v))})
    