#!/bin/bash

precondition_satisfied=false

while ! $precondition_satisfied
do
    echo "Testing precondition: 'hive' catalog accessible ..."
    ./trino --server "$TRINO_ENDPOINT" --catalog hive --schema default --user trino --execute "SHOW TABLES;" && \
        { echo "'hive' is now accessible" && precondition_satisfied=true ; } || \
        precondition_satisfied=false
done

echo "Initializing database..."
INIT_SQL_SCRIPT="
    -- upsert_at is not necessary but gives some insights on the record's age
    CREATE TABLE IF NOT EXISTS patients (
        -- shared columns
        owner_id VARCHAR,
        id VARCHAR,
        scope VARCHAR,

        -- clinical data
        current_diagnose INTEGER,
        age INTEGER,
        sex BOOLEAN,
        right_handed BOOLEAN,
        schooling INTEGER,
        egfr INTEGER,
        first_visit DATE,
        diagnose_date DATE,
        a BOOLEAN,
        t BOOLEAN,
        n BOOLEAN,
        memoria BOOLEAN,
        memoria_esordio DATE,
        fx_esecutive BOOLEAN,
        fx_esecutive_esordio DATE,
        fx_visuo_spaziali BOOLEAN,
        fx_visuo_spaziali_esordio DATE,
        linguaggio BOOLEAN,
        linguaggio_esordio DATE,
        fx_pratto_gnosiche BOOLEAN,
        fx_pratto_gnosiche_esordio DATE,
        social_cognition BOOLEAN,
        social_cognition_esordio DATE,
        comportamento BOOLEAN,
        comportamento_esordio DATE,
        extrapiramidale BOOLEAN,
        adl INTEGER,
        iadl DOUBLE,
        cdr DOUBLE,
        cdr_sob VARCHAR,
        tau_totale_liquor INTEGER,
        ptau_181_liquor DOUBLE,
        ttau_ptau DOUBLE,
        mta INTEGER,
        fazekas INTEGER,
        koedam INTEGER,
        gca INTEGER,
        vascular INTEGER,
        pet_fdg BOOLEAN,
        spect INTEGER,
        pet_a INTEGER,
        mmse_raw INTEGER,
        mmse_corr DOUBLE,
        fab_raw INTEGER,
        fab_corr DOUBLE,
        memoria_di_prosa_immediata_raw DOUBLE,
        memoria_di_prosa_immediata_corr DOUBLE,
        memoria_di_prosa_differita_raw DOUBLE,
        memoria_di_prosa_differita_corr DOUBLE,
        fcsrt_immediate_free_recall_raw INTEGER,
        fcsrt_immediate_free_recall_corr DOUBLE,
        fcsrt_delayed_free_recall_raw INTEGER,
        fcsrt_delayed_free_recall_corr DOUBLE,
        fcsrt_isc DOUBLE,
        fcsrt_itr INTEGER,
        fcsrt_dtr INTEGER,
        ravlt_immediato_raw INTEGER,
        ravlt_immediato_corr DOUBLE,
        ravlt_differito_raw INTEGER,
        ravlt_differito_corr DOUBLE,
        ravlt_recognition DOUBLE,
        digit_span_diretto_raw INTEGER,
        digit_span_diretto_corr DOUBLE,
        digit_span_inverso_raw INTEGER,
        digit_span_inverso_corr DOUBLE,
        corsi_block_tapping_test_raw INTEGER,
        corsi_block_tapping_test_corr DOUBLE,
        figura_di_rey_differita INTEGER,
        figura_di_rey_differita_corr DOUBLE,
        matrici_attentive_raw INTEGER,
        matrici_attentive_corr DOUBLE,
        tmt_a_raw INTEGER,
        tmt_a_corr INTEGER,
        tmt_b_raw INTEGER,
        tmt_b_corr INTEGER,
        stroop_test_tempo_raw DOUBLE,
        stroop_test_tempo_corr DOUBLE,
        stroop_test_errori_raw DOUBLE,
        stroop_test_errori_corr DOUBLE,
        fluenza_verbale_fonemica_raw DOUBLE,
        fluenza_verbale_fonemica_corr DOUBLE,
        fluenza_verbale_semantica_raw DOUBLE,
        fluenza_verbale_semantica_corr DOUBLE,
        clock_drawing_test_raw DOUBLE,
        figura_di_rey_copia INTEGER,
        test_di_prassia_costruttiva_raw INTEGER,
        test_di_prassia_costruttiva_corr DOUBLE,
        gds INTEGER,
        bdi INTEGER,
        stai_i INTEGER,
        stai_ii INTEGER,
        social_cognition_gs_raw INTEGER,
        social_cognition_gs_corr DOUBLE,
        social_cognition_ia_raw INTEGER,
        social_cognition_ia_corr DOUBLE,
        social_cognition_ea_raw INTEGER,
        social_cognition_ea_corr DOUBLE,
        social_cognition_ci_raw INTEGER,
        social_cognition_ci_corr DOUBLE,
        cri_totale_raw INTEGER,
        cri_tempo_libero_raw INTEGER,
        cri_lavoro_raw INTEGER,
        cri_scuola_raw INTEGER,
        test_linguistici_nndd DOUBLE,
        clinical_data_upsert_at TIMESTAMP,
    
        -- mir results
        hsa_miR_1539 DOUBLE,
        hsa_miR_6840_3p DOUBLE,
        hsa_miR_6836_3p DOUBLE,
        hsa_miR_4667_5p DOUBLE,
        hsa_miR_208a_5p DOUBLE,
        hsa_miR_6885_5p DOUBLE,
        hsa_miR_1306_5p DOUBLE,
        hsa_miR_3184_5p DOUBLE,
        hsa_miR_4649_5p DOUBLE,
        hsa_miR_6859_3p DOUBLE,
        hsa_miR_6829_3p DOUBLE,
        hsa_miR_3622a_3p DOUBLE,
        hsa_miR_4664_3p DOUBLE,
        hsa_miR_6776_3p DOUBLE,
        hsa_miR_135a_3p DOUBLE,
        hsa_miR_6875_5p DOUBLE,
        hsa_miR_3646 DOUBLE,
        hsa_miR_3614_5p DOUBLE,
        hsa_miR_128_1_5p DOUBLE,
        hsa_miR_6813_3p DOUBLE,
        hsa_miR_6752_5p DOUBLE,
        hsa_miR_204_3p DOUBLE,
        hsa_miR_6806_5p DOUBLE,
        hsa_miR_1538 DOUBLE,
        hsa_miR_6887_3p DOUBLE,
        hsa_miR_5088_3p DOUBLE,
        hsa_miR_6743_5p DOUBLE,
        hsa_miR_4274 DOUBLE,
        hsa_miR_5585_3p DOUBLE,
        hsa_miR_4787_5p DOUBLE,
        hsa_miR_320b DOUBLE,
        hsa_miR_6870_3p DOUBLE,
        hsa_miR_199a_5p DOUBLE,
        hsa_miR_4290 DOUBLE,
        hsa_miR_6721_5p DOUBLE,
        hsa_miR_4728_3p DOUBLE,
        hsa_miR_3691_5p DOUBLE,
        hsa_miR_4440 DOUBLE,
        hsa_miR_874_3p DOUBLE,
        hsa_miR_27a_3p DOUBLE,
        hsa_miR_2278 DOUBLE,
        hsa_miR_150_3p DOUBLE,
        hsa_miR_4716_3p DOUBLE,
        hsa_miR_211_5p DOUBLE,
        hsa_miR_125a_5p DOUBLE,
        hsa_miR_4741 DOUBLE,
        hsa_miR_3122 DOUBLE,
        hsa_miR_3180_5p DOUBLE,
        hsa_miR_574_3p DOUBLE,
        hsa_miR_150_5p DOUBLE,
        hsa_miR_133b DOUBLE,
        hsa_miR_30c_5p DOUBLE,
        hsa_miR_212_3p DOUBLE,
        hsa_miR_92b_3p DOUBLE,
        hsa_miR_504_3p DOUBLE,
        ath_miR_159a DOUBLE,
        mir_results_upsert_at TIMESTAMP
    )
    WITH (
        --format = 'PARQUET'
        format='ORC',
        transactional=true
    );

    CREATE TABLE IF NOT EXISTS patients_data_history (
        -- shared columns
        owner_id VARCHAR,
        id VARCHAR,
        scope VARCHAR,

        current_diagnose INTEGER,
        age INTEGER,
        sex BOOLEAN,
        right_handed BOOLEAN,
        schooling INTEGER,
        egfr INTEGER,
        first_visit DATE,
        diagnose_date DATE,
        a BOOLEAN,
        t BOOLEAN,
        n BOOLEAN,
        memoria BOOLEAN,
        memoria_esordio DATE,
        fx_esecutive BOOLEAN,
        fx_esecutive_esordio DATE,
        fx_visuo_spaziali BOOLEAN,
        fx_visuo_spaziali_esordio DATE,
        linguaggio BOOLEAN,
        linguaggio_esordio DATE,
        fx_pratto_gnosiche BOOLEAN,
        fx_pratto_gnosiche_esordio DATE,
        social_cognition BOOLEAN,
        social_cognition_esordio DATE,
        comportamento BOOLEAN,
        comportamento_esordio DATE,
        extrapiramidale BOOLEAN,
        adl INTEGER,
        iadl DOUBLE,
        cdr DOUBLE,
        cdr_sob VARCHAR,
        tau_totale_liquor INTEGER,
        ptau_181_liquor DOUBLE,
        ttau_ptau DOUBLE,
        mta INTEGER,
        fazekas INTEGER,
        koedam INTEGER,
        gca INTEGER,
        vascular INTEGER,
        pet_fdg BOOLEAN,
        spect INTEGER,
        pet_a INTEGER,
        mmse_raw INTEGER,
        mmse_corr DOUBLE,
        fab_raw INTEGER,
        fab_corr DOUBLE,
        memoria_di_prosa_immediata_raw DOUBLE,
        memoria_di_prosa_immediata_corr DOUBLE,
        memoria_di_prosa_differita_raw DOUBLE,
        memoria_di_prosa_differita_corr DOUBLE,
        fcsrt_immediate_free_recall_raw INTEGER,
        fcsrt_immediate_free_recall_corr DOUBLE,
        fcsrt_delayed_free_recall_raw INTEGER,
        fcsrt_delayed_free_recall_corr DOUBLE,
        fcsrt_isc DOUBLE,
        fcsrt_itr INTEGER,
        fcsrt_dtr INTEGER,
        ravlt_immediato_raw INTEGER,
        ravlt_immediato_corr DOUBLE,
        ravlt_differito_raw INTEGER,
        ravlt_differito_corr DOUBLE,
        ravlt_recognition DOUBLE,
        digit_span_diretto_raw INTEGER,
        digit_span_diretto_corr DOUBLE,
        digit_span_inverso_raw INTEGER,
        digit_span_inverso_corr DOUBLE,
        corsi_block_tapping_test_raw INTEGER,
        corsi_block_tapping_test_corr DOUBLE,
        figura_di_rey_differita INTEGER,
        figura_di_rey_differita_corr DOUBLE,
        matrici_attentive_raw INTEGER,
        matrici_attentive_corr DOUBLE,
        tmt_a_raw INTEGER,
        tmt_a_corr INTEGER,
        tmt_b_raw INTEGER,
        tmt_b_corr INTEGER,
        stroop_test_tempo_raw DOUBLE,
        stroop_test_tempo_corr DOUBLE,
        stroop_test_errori_raw DOUBLE,
        stroop_test_errori_corr DOUBLE,
        fluenza_verbale_fonemica_raw DOUBLE,
        fluenza_verbale_fonemica_corr DOUBLE,
        fluenza_verbale_semantica_raw DOUBLE,
        fluenza_verbale_semantica_corr DOUBLE,
        clock_drawing_test_raw DOUBLE,
        figura_di_rey_copia INTEGER,
        test_di_prassia_costruttiva_raw INTEGER,
        test_di_prassia_costruttiva_corr DOUBLE,
        gds INTEGER,
        bdi INTEGER,
        stai_i INTEGER,
        stai_ii INTEGER,
        social_cognition_gs_raw INTEGER,
        social_cognition_gs_corr DOUBLE,
        social_cognition_ia_raw INTEGER,
        social_cognition_ia_corr DOUBLE,
        social_cognition_ea_raw INTEGER,
        social_cognition_ea_corr DOUBLE,
        social_cognition_ci_raw INTEGER,
        social_cognition_ci_corr DOUBLE,
        cri_totale_raw INTEGER,
        cri_tempo_libero_raw INTEGER,
        cri_lavoro_raw INTEGER,
        cri_scuola_raw INTEGER,
        test_linguistici_nndd DOUBLE,
        upsert_at TIMESTAMP
    )
    WITH (
        --format = 'PARQUET'
        format='ORC'
    );

    CREATE TABLE IF NOT EXISTS mir_results_history (
        -- shared columns
        owner_id VARCHAR,
        id VARCHAR,
        scope VARCHAR,

        hsa_miR_1539 DOUBLE,
        hsa_miR_6840_3p DOUBLE,
        hsa_miR_6836_3p DOUBLE,
        hsa_miR_4667_5p DOUBLE,
        hsa_miR_208a_5p DOUBLE,
        hsa_miR_6885_5p DOUBLE,
        hsa_miR_1306_5p DOUBLE,
        hsa_miR_3184_5p DOUBLE,
        hsa_miR_4649_5p DOUBLE,
        hsa_miR_6859_3p DOUBLE,
        hsa_miR_6829_3p DOUBLE,
        hsa_miR_3622a_3p DOUBLE,
        hsa_miR_4664_3p DOUBLE,
        hsa_miR_6776_3p DOUBLE,
        hsa_miR_135a_3p DOUBLE,
        hsa_miR_6875_5p DOUBLE,
        hsa_miR_3646 DOUBLE,
        hsa_miR_3614_5p DOUBLE,
        hsa_miR_128_1_5p DOUBLE,
        hsa_miR_6813_3p DOUBLE,
        hsa_miR_6752_5p DOUBLE,
        hsa_miR_204_3p DOUBLE,
        hsa_miR_6806_5p DOUBLE,
        hsa_miR_1538 DOUBLE,
        hsa_miR_6887_3p DOUBLE,
        hsa_miR_5088_3p DOUBLE,
        hsa_miR_6743_5p DOUBLE,
        hsa_miR_4274 DOUBLE,
        hsa_miR_5585_3p DOUBLE,
        hsa_miR_4787_5p DOUBLE,
        hsa_miR_320b DOUBLE,
        hsa_miR_6870_3p DOUBLE,
        hsa_miR_199a_5p DOUBLE,
        hsa_miR_4290 DOUBLE,
        hsa_miR_6721_5p DOUBLE,
        hsa_miR_4728_3p DOUBLE,
        hsa_miR_3691_5p DOUBLE,
        hsa_miR_4440 DOUBLE,
        hsa_miR_874_3p DOUBLE,
        hsa_miR_27a_3p DOUBLE,
        hsa_miR_2278 DOUBLE,
        hsa_miR_150_3p DOUBLE,
        hsa_miR_4716_3p DOUBLE,
        hsa_miR_211_5p DOUBLE,
        hsa_miR_125a_5p DOUBLE,
        hsa_miR_4741 DOUBLE,
        hsa_miR_3122 DOUBLE,
        hsa_miR_3180_5p DOUBLE,
        hsa_miR_574_3p DOUBLE,
        hsa_miR_150_5p DOUBLE,
        hsa_miR_133b DOUBLE,
        hsa_miR_30c_5p DOUBLE,
        hsa_miR_212_3p DOUBLE,
        hsa_miR_92b_3p DOUBLE,
        hsa_miR_504_3p DOUBLE,
        ath_miR_159a DOUBLE,
        upsert_at TIMESTAMP
    )
    WITH (
        --format = 'PARQUET'
        format='ORC'
    );

    CREATE OR REPLACE VIEW patients_training AS
    SELECT owner_id, id, current_diagnose, age, sex, right_handed, schooling, egfr, first_visit, diagnose_date, a, t, n, memoria, memoria_esordio, fx_esecutive, fx_esecutive_esordio, fx_visuo_spaziali, fx_visuo_spaziali_esordio, linguaggio, linguaggio_esordio, fx_pratto_gnosiche, fx_pratto_gnosiche_esordio, social_cognition, social_cognition_esordio, comportamento, comportamento_esordio, extrapiramidale, adl, iadl, cdr, cdr_sob, tau_totale_liquor, ptau_181_liquor, ttau_ptau, mta, fazekas, koedam, gca, vascular, pet_fdg, spect, pet_a, mmse_raw, mmse_corr, fab_raw, fab_corr, memoria_di_prosa_immediata_raw, memoria_di_prosa_immediata_corr, memoria_di_prosa_differita_raw, memoria_di_prosa_differita_corr, fcsrt_immediate_free_recall_raw, fcsrt_immediate_free_recall_corr, fcsrt_delayed_free_recall_raw, fcsrt_delayed_free_recall_corr, fcsrt_isc, fcsrt_itr, fcsrt_dtr, ravlt_immediato_raw, ravlt_immediato_corr, ravlt_differito_raw, ravlt_differito_corr, ravlt_recognition, digit_span_diretto_raw, digit_span_diretto_corr, digit_span_inverso_raw, digit_span_inverso_corr, corsi_block_tapping_test_raw, corsi_block_tapping_test_corr, figura_di_rey_differita, figura_di_rey_differita_corr, matrici_attentive_raw, matrici_attentive_corr, tmt_a_raw, tmt_a_corr, tmt_b_raw, tmt_b_corr, stroop_test_tempo_raw, stroop_test_tempo_corr, stroop_test_errori_raw, stroop_test_errori_corr, fluenza_verbale_fonemica_raw, fluenza_verbale_fonemica_corr, fluenza_verbale_semantica_raw, fluenza_verbale_semantica_corr, clock_drawing_test_raw, figura_di_rey_copia, test_di_prassia_costruttiva_raw, test_di_prassia_costruttiva_corr, gds, bdi, stai_i, stai_ii, social_cognition_gs_raw, social_cognition_gs_corr, social_cognition_ia_raw, social_cognition_ia_corr, social_cognition_ea_raw, social_cognition_ea_corr, social_cognition_ci_raw, social_cognition_ci_corr, cri_totale_raw, cri_tempo_libero_raw, cri_lavoro_raw, cri_scuola_raw, test_linguistici_nndd, hsa_miR_1539, hsa_miR_6840_3p, hsa_miR_6836_3p, hsa_miR_4667_5p, hsa_miR_208a_5p, hsa_miR_6885_5p, hsa_miR_1306_5p, hsa_miR_3184_5p, hsa_miR_4649_5p, hsa_miR_6859_3p, hsa_miR_6829_3p, hsa_miR_3622a_3p, hsa_miR_4664_3p, hsa_miR_6776_3p, hsa_miR_135a_3p, hsa_miR_6875_5p, hsa_miR_3646, hsa_miR_3614_5p, hsa_miR_128_1_5p, hsa_miR_6813_3p, hsa_miR_6752_5p, hsa_miR_204_3p, hsa_miR_6806_5p, hsa_miR_1538, hsa_miR_6887_3p, hsa_miR_5088_3p, hsa_miR_6743_5p, hsa_miR_4274, hsa_miR_5585_3p, hsa_miR_4787_5p, hsa_miR_320b, hsa_miR_6870_3p, hsa_miR_199a_5p, hsa_miR_4290, hsa_miR_6721_5p, hsa_miR_4728_3p, hsa_miR_3691_5p, hsa_miR_4440, hsa_miR_874_3p, hsa_miR_27a_3p, hsa_miR_2278, hsa_miR_150_3p, hsa_miR_4716_3p, hsa_miR_211_5p, hsa_miR_125a_5p, hsa_miR_4741, hsa_miR_3122, hsa_miR_3180_5p, hsa_miR_574_3p, hsa_miR_150_5p, hsa_miR_133b, hsa_miR_30c_5p, hsa_miR_212_3p, hsa_miR_92b_3p, hsa_miR_504_3p, ath_miR_159a
    FROM patients
    WHERE scope = 'training';

    CREATE OR REPLACE VIEW patients_inference AS
    SELECT owner_id, id, current_diagnose, age, sex, right_handed, schooling, egfr, first_visit, diagnose_date, a, t, n, memoria, memoria_esordio, fx_esecutive, fx_esecutive_esordio, fx_visuo_spaziali, fx_visuo_spaziali_esordio, linguaggio, linguaggio_esordio, fx_pratto_gnosiche, fx_pratto_gnosiche_esordio, social_cognition, social_cognition_esordio, comportamento, comportamento_esordio, extrapiramidale, adl, iadl, cdr, cdr_sob, tau_totale_liquor, ptau_181_liquor, ttau_ptau, mta, fazekas, koedam, gca, vascular, pet_fdg, spect, pet_a, mmse_raw, mmse_corr, fab_raw, fab_corr, memoria_di_prosa_immediata_raw, memoria_di_prosa_immediata_corr, memoria_di_prosa_differita_raw, memoria_di_prosa_differita_corr, fcsrt_immediate_free_recall_raw, fcsrt_immediate_free_recall_corr, fcsrt_delayed_free_recall_raw, fcsrt_delayed_free_recall_corr, fcsrt_isc, fcsrt_itr, fcsrt_dtr, ravlt_immediato_raw, ravlt_immediato_corr, ravlt_differito_raw, ravlt_differito_corr, ravlt_recognition, digit_span_diretto_raw, digit_span_diretto_corr, digit_span_inverso_raw, digit_span_inverso_corr, corsi_block_tapping_test_raw, corsi_block_tapping_test_corr, figura_di_rey_differita, figura_di_rey_differita_corr, matrici_attentive_raw, matrici_attentive_corr, tmt_a_raw, tmt_a_corr, tmt_b_raw, tmt_b_corr, stroop_test_tempo_raw, stroop_test_tempo_corr, stroop_test_errori_raw, stroop_test_errori_corr, fluenza_verbale_fonemica_raw, fluenza_verbale_fonemica_corr, fluenza_verbale_semantica_raw, fluenza_verbale_semantica_corr, clock_drawing_test_raw, figura_di_rey_copia, test_di_prassia_costruttiva_raw, test_di_prassia_costruttiva_corr, gds, bdi, stai_i, stai_ii, social_cognition_gs_raw, social_cognition_gs_corr, social_cognition_ia_raw, social_cognition_ia_corr, social_cognition_ea_raw, social_cognition_ea_corr, social_cognition_ci_raw, social_cognition_ci_corr, cri_totale_raw, cri_tempo_libero_raw, cri_lavoro_raw, cri_scuola_raw, test_linguistici_nndd, hsa_miR_1539, hsa_miR_6840_3p, hsa_miR_6836_3p, hsa_miR_4667_5p, hsa_miR_208a_5p, hsa_miR_6885_5p, hsa_miR_1306_5p, hsa_miR_3184_5p, hsa_miR_4649_5p, hsa_miR_6859_3p, hsa_miR_6829_3p, hsa_miR_3622a_3p, hsa_miR_4664_3p, hsa_miR_6776_3p, hsa_miR_135a_3p, hsa_miR_6875_5p, hsa_miR_3646, hsa_miR_3614_5p, hsa_miR_128_1_5p, hsa_miR_6813_3p, hsa_miR_6752_5p, hsa_miR_204_3p, hsa_miR_6806_5p, hsa_miR_1538, hsa_miR_6887_3p, hsa_miR_5088_3p, hsa_miR_6743_5p, hsa_miR_4274, hsa_miR_5585_3p, hsa_miR_4787_5p, hsa_miR_320b, hsa_miR_6870_3p, hsa_miR_199a_5p, hsa_miR_4290, hsa_miR_6721_5p, hsa_miR_4728_3p, hsa_miR_3691_5p, hsa_miR_4440, hsa_miR_874_3p, hsa_miR_27a_3p, hsa_miR_2278, hsa_miR_150_3p, hsa_miR_4716_3p, hsa_miR_211_5p, hsa_miR_125a_5p, hsa_miR_4741, hsa_miR_3122, hsa_miR_3180_5p, hsa_miR_574_3p, hsa_miR_150_5p, hsa_miR_133b, hsa_miR_30c_5p, hsa_miR_212_3p, hsa_miR_92b_3p, hsa_miR_504_3p, ath_miR_159a
    FROM patients
    WHERE scope = 'inference';
"

./trino --server "$TRINO_ENDPOINT" --catalog hive --schema default --user trino --execute "$INIT_SQL_SCRIPT" && \
    echo "Initialization complete."