[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "prin-task-api-utils"
version = "1.0.0"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.in"]}

[tool.setuptools.packages.find]
where = ["."]